name: Build & Deploy on Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install yarn ğŸ”§
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Generate static website ğŸ”§
        run: |
          yarn install
          yarn generate

      - name: Build & Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.github_token }}
          branch: gh-pages
          folder: dist
          clean: true
